/**
 * Tipos de la base de datos. NO editar a mano.
 * Regenerar tras cada migración con:  npm run db:types
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      app_settings: {
        Row: {
          id: boolean;
          app_name: string;
          tagline: string;
          description: string;
          logo_url: string | null;
          icon_url: string | null;
          primary_color: string;
          accent_color: string;
          text_color: string;
          updated_by: string | null;
          updated_at: string;
          splash_enabled: boolean;
          onboarding_enabled: boolean;
          login_title: string | null;
          login_subtitle: string | null;
          login_image_url: string | null;
          register_title: string | null;
          register_subtitle: string | null;
          register_image_url: string | null;
          social_google: boolean;
          social_facebook: boolean;
          terms_url: string | null;
          privacy_url: string | null;
          sound_settings: Json;
          splash_image_url: string | null;
          splash_title: string | null;
          splash_subtitle: string | null;
          social_apple: boolean;
          splash_seconds: number;
          banner_rotation_seconds: number;
        };
        Insert: {
          id?: boolean;
          app_name?: string;
          tagline?: string;
          description?: string;
          logo_url?: string | null;
          icon_url?: string | null;
          primary_color?: string;
          accent_color?: string;
          text_color?: string;
          updated_by?: string | null;
          updated_at?: string;
          splash_enabled?: boolean;
          onboarding_enabled?: boolean;
          login_title?: string | null;
          login_subtitle?: string | null;
          login_image_url?: string | null;
          register_title?: string | null;
          register_subtitle?: string | null;
          register_image_url?: string | null;
          social_google?: boolean;
          social_facebook?: boolean;
          terms_url?: string | null;
          privacy_url?: string | null;
          sound_settings?: Json;
          splash_image_url?: string | null;
          splash_title?: string | null;
          splash_subtitle?: string | null;
          social_apple?: boolean;
          splash_seconds?: number;
          banner_rotation_seconds?: number;
        };
        Update: {
          id?: boolean;
          app_name?: string;
          tagline?: string;
          description?: string;
          logo_url?: string | null;
          icon_url?: string | null;
          primary_color?: string;
          accent_color?: string;
          text_color?: string;
          updated_by?: string | null;
          updated_at?: string;
          splash_enabled?: boolean;
          onboarding_enabled?: boolean;
          login_title?: string | null;
          login_subtitle?: string | null;
          login_image_url?: string | null;
          register_title?: string | null;
          register_subtitle?: string | null;
          register_image_url?: string | null;
          social_google?: boolean;
          social_facebook?: boolean;
          terms_url?: string | null;
          privacy_url?: string | null;
          sound_settings?: Json;
          splash_image_url?: string | null;
          splash_title?: string | null;
          splash_subtitle?: string | null;
          social_apple?: boolean;
          splash_seconds?: number;
          banner_rotation_seconds?: number;
        };
        Relationships: [];
      };
      banners: {
        Row: {
          id: string;
          restaurant_id: string | null;
          title: string | null;
          subtitle: string | null;
          image_url: string;
          link_url: string | null;
          position: number;
          is_active: boolean;
          starts_at: string | null;
          ends_at: string | null;
          created_at: string;
          updated_at: string;
          is_pinned: boolean;
          pinned_cities: string[];
        };
        Insert: {
          id?: string;
          restaurant_id?: string | null;
          title?: string | null;
          subtitle?: string | null;
          image_url: string;
          link_url?: string | null;
          position?: number;
          is_active?: boolean;
          starts_at?: string | null;
          ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
          is_pinned?: boolean;
          pinned_cities?: string[];
        };
        Update: {
          id?: string;
          restaurant_id?: string | null;
          title?: string | null;
          subtitle?: string | null;
          image_url?: string;
          link_url?: string | null;
          position?: number;
          is_active?: boolean;
          starts_at?: string | null;
          ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
          is_pinned?: boolean;
          pinned_cities?: string[];
        };
        Relationships: [];
      };
      cash_movements: {
        Row: {
          id: string;
          session_id: string;
          restaurant_id: string;
          kind: Enums<"cash_movement_kind">;
          amount_cents: number;
          method: Enums<"payment_method">;
          reason: string;
          courier_id: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          restaurant_id: string;
          kind: Enums<"cash_movement_kind">;
          amount_cents: number;
          method?: Enums<"payment_method">;
          reason: string;
          courier_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          restaurant_id?: string;
          kind?: Enums<"cash_movement_kind">;
          amount_cents?: number;
          method?: Enums<"payment_method">;
          reason?: string;
          courier_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      cash_sessions: {
        Row: {
          id: string;
          restaurant_id: string;
          status: Enums<"cash_session_status">;
          opened_at: string;
          opened_by: string | null;
          opening_float_cents: number;
          closed_at: string | null;
          closed_by: string | null;
          counted_cents: number | null;
          expected_cents: number | null;
          variance_cents: number | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          status?: Enums<"cash_session_status">;
          opened_at?: string;
          opened_by?: string | null;
          opening_float_cents?: number;
          closed_at?: string | null;
          closed_by?: string | null;
          counted_cents?: number | null;
          expected_cents?: number | null;
          variance_cents?: number | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          status?: Enums<"cash_session_status">;
          opened_at?: string;
          opened_by?: string | null;
          opening_float_cents?: number;
          closed_at?: string | null;
          closed_by?: string | null;
          counted_cents?: number | null;
          expected_cents?: number | null;
          variance_cents?: number | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      catalog_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          icon: string | null;
          position: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          icon?: string | null;
          position?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          icon?: string | null;
          position?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          description: string | null;
          image_url: string | null;
          position: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          name: string;
          description?: string | null;
          image_url?: string | null;
          position?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          name?: string;
          description?: string | null;
          image_url?: string | null;
          position?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      coupon_categories: {
        Row: {
          coupon_id: string;
          category_id: string;
        };
        Insert: {
          coupon_id: string;
          category_id: string;
        };
        Update: {
          coupon_id?: string;
          category_id?: string;
        };
        Relationships: [];
      };
      coupon_products: {
        Row: {
          coupon_id: string;
          product_id: string;
        };
        Insert: {
          coupon_id: string;
          product_id: string;
        };
        Update: {
          coupon_id?: string;
          product_id?: string;
        };
        Relationships: [];
      };
      coupon_redemptions: {
        Row: {
          id: string;
          coupon_id: string;
          order_id: string | null;
          restaurant_id: string | null;
          customer_id: string | null;
          discount_cents: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          coupon_id: string;
          order_id?: string | null;
          restaurant_id?: string | null;
          customer_id?: string | null;
          discount_cents?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          coupon_id?: string;
          order_id?: string | null;
          restaurant_id?: string | null;
          customer_id?: string | null;
          discount_cents?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          restaurant_id: string | null;
          kind: Enums<"coupon_kind">;
          percentage: number | null;
          value_cents: number | null;
          max_discount_cents: number | null;
          target: Enums<"coupon_target">;
          min_order_cents: number;
          starts_at: string;
          ends_at: string | null;
          max_redemptions: number | null;
          max_per_customer: number;
          redemptions_count: number;
          is_active: boolean;
          description: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          restaurant_id?: string | null;
          kind: Enums<"coupon_kind">;
          percentage?: number | null;
          value_cents?: number | null;
          max_discount_cents?: number | null;
          target?: Enums<"coupon_target">;
          min_order_cents?: number;
          starts_at?: string;
          ends_at?: string | null;
          max_redemptions?: number | null;
          max_per_customer?: number;
          redemptions_count?: number;
          is_active?: boolean;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          restaurant_id?: string | null;
          kind?: Enums<"coupon_kind">;
          percentage?: number | null;
          value_cents?: number | null;
          max_discount_cents?: number | null;
          target?: Enums<"coupon_target">;
          min_order_cents?: number;
          starts_at?: string;
          ends_at?: string | null;
          max_redemptions?: number | null;
          max_per_customer?: number;
          redemptions_count?: number;
          is_active?: boolean;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      couriers: {
        Row: {
          id: string;
          user_id: string;
          phone: string | null;
          vehicle: string;
          status: Enums<"courier_status">;
          city: string | null;
          lat: number | null;
          lng: number | null;
          location_updated_at: string | null;
          rating: number;
          rating_count: number;
          deliveries_count: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          city_slug: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          phone?: string | null;
          vehicle?: string;
          status?: Enums<"courier_status">;
          city?: string | null;
          lat?: number | null;
          lng?: number | null;
          location_updated_at?: string | null;
          rating?: number;
          rating_count?: number;
          deliveries_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          city_slug?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          phone?: string | null;
          vehicle?: string;
          status?: Enums<"courier_status">;
          city?: string | null;
          lat?: number | null;
          lng?: number | null;
          location_updated_at?: string | null;
          rating?: number;
          rating_count?: number;
          deliveries_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          city_slug?: string | null;
        };
        Relationships: [];
      };
      customer_coupons: {
        Row: {
          user_id: string;
          coupon_id: string;
          saved_at: string;
        };
        Insert: {
          user_id: string;
          coupon_id: string;
          saved_at?: string;
        };
        Update: {
          user_id?: string;
          coupon_id?: string;
          saved_at?: string;
        };
        Relationships: [];
      };
      favorites: {
        Row: {
          user_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          product_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      money_audit: {
        Row: {
          id: number;
          restaurant_id: string;
          entity: string;
          entity_id: string;
          action: string;
          before_cents: number | null;
          after_cents: number | null;
          reason: string | null;
          actor_id: string | null;
          actor_role: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          restaurant_id: string;
          entity: string;
          entity_id: string;
          action: string;
          before_cents?: number | null;
          after_cents?: number | null;
          reason?: string | null;
          actor_id?: string | null;
          actor_role?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          restaurant_id?: string;
          entity?: string;
          entity_id?: string;
          action?: string;
          before_cents?: number | null;
          after_cents?: number | null;
          reason?: string | null;
          actor_id?: string | null;
          actor_role?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          title: string;
          body: string | null;
          image_url: string | null;
          link_url: string | null;
          link_label: string | null;
          audience: Enums<"notification_audience">;
          cities: string[];
          starts_at: string;
          ends_at: string | null;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          body?: string | null;
          image_url?: string | null;
          link_url?: string | null;
          link_label?: string | null;
          audience?: Enums<"notification_audience">;
          cities?: string[];
          starts_at?: string;
          ends_at?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          body?: string | null;
          image_url?: string | null;
          link_url?: string | null;
          link_label?: string | null;
          audience?: Enums<"notification_audience">;
          cities?: string[];
          starts_at?: string;
          ends_at?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      onboarding_slides: {
        Row: {
          id: string;
          title: string;
          subtitle: string | null;
          image_url: string | null;
          position: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          subtitle?: string | null;
          image_url?: string | null;
          position?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          subtitle?: string | null;
          image_url?: string | null;
          position?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      option_groups: {
        Row: {
          id: string;
          product_id: string;
          name: string;
          min_select: number;
          max_select: number;
          is_required: boolean;
          position: number;
        };
        Insert: {
          id?: string;
          product_id: string;
          name: string;
          min_select?: number;
          max_select?: number;
          is_required?: boolean;
          position?: number;
        };
        Update: {
          id?: string;
          product_id?: string;
          name?: string;
          min_select?: number;
          max_select?: number;
          is_required?: boolean;
          position?: number;
        };
        Relationships: [];
      };
      options: {
        Row: {
          id: string;
          group_id: string;
          name: string;
          price_delta_cents: number;
          is_default: boolean;
          is_available: boolean;
          position: number;
        };
        Insert: {
          id?: string;
          group_id: string;
          name: string;
          price_delta_cents?: number;
          is_default?: boolean;
          is_available?: boolean;
          position?: number;
        };
        Update: {
          id?: string;
          group_id?: string;
          name?: string;
          price_delta_cents?: number;
          is_default?: boolean;
          is_available?: boolean;
          position?: number;
        };
        Relationships: [];
      };
      order_events: {
        Row: {
          id: string;
          order_id: string;
          status: Enums<"order_status">;
          note: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          status: Enums<"order_status">;
          note?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          status?: Enums<"order_status">;
          note?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          name_snapshot: string;
          image_snapshot: string | null;
          unit_price_cents: number;
          quantity: number;
          options: Json;
          options_total_cents: number;
          line_total_cents: number;
          status: Enums<"order_item_status">;
          notes: string | null;
          created_at: string;
          voided_at: string | null;
          voided_by: string | null;
          void_reason: string | null;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id?: string | null;
          name_snapshot: string;
          image_snapshot?: string | null;
          unit_price_cents: number;
          quantity?: number;
          options?: Json;
          options_total_cents?: number;
          line_total_cents?: number;
          status?: Enums<"order_item_status">;
          notes?: string | null;
          created_at?: string;
          voided_at?: string | null;
          voided_by?: string | null;
          void_reason?: string | null;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string | null;
          name_snapshot?: string;
          image_snapshot?: string | null;
          unit_price_cents?: number;
          quantity?: number;
          options?: Json;
          options_total_cents?: number;
          line_total_cents?: number;
          status?: Enums<"order_item_status">;
          notes?: string | null;
          created_at?: string;
          voided_at?: string | null;
          voided_by?: string | null;
          void_reason?: string | null;
        };
        Relationships: [];
      };
      order_payments: {
        Row: {
          id: string;
          order_id: string;
          restaurant_id: string;
          kind: Enums<"payment_entry_kind">;
          amount_cents: number;
          method: Enums<"payment_method">;
          note: string | null;
          reason: string | null;
          created_by: string | null;
          courier_id: string | null;
          cash_settled_at: string | null;
          cash_settled_by: string | null;
          created_at: string;
          cash_session_id: string | null;
        };
        Insert: {
          id?: string;
          order_id: string;
          restaurant_id: string;
          kind?: Enums<"payment_entry_kind">;
          amount_cents: number;
          method: Enums<"payment_method">;
          note?: string | null;
          reason?: string | null;
          created_by?: string | null;
          courier_id?: string | null;
          cash_settled_at?: string | null;
          cash_settled_by?: string | null;
          created_at?: string;
          cash_session_id?: string | null;
        };
        Update: {
          id?: string;
          order_id?: string;
          restaurant_id?: string;
          kind?: Enums<"payment_entry_kind">;
          amount_cents?: number;
          method?: Enums<"payment_method">;
          note?: string | null;
          reason?: string | null;
          created_by?: string | null;
          courier_id?: string | null;
          cash_settled_at?: string | null;
          cash_settled_by?: string | null;
          created_at?: string;
          cash_session_id?: string | null;
        };
        Relationships: [];
      };
      order_push_targets: {
        Row: {
          order_id: string;
          subscription_id: string;
          created_at: string;
        };
        Insert: {
          order_id: string;
          subscription_id: string;
          created_at?: string;
        };
        Update: {
          order_id?: string;
          subscription_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          restaurant_id: string;
          table_id: string | null;
          customer_id: string | null;
          public_token: string;
          code: string;
          type: Enums<"order_type">;
          status: Enums<"order_status">;
          customer_name: string | null;
          customer_phone: string | null;
          customer_email: string | null;
          address: string | null;
          address_notes: string | null;
          lat: number | null;
          lng: number | null;
          payment_method: Enums<"payment_method">;
          payment_status: Enums<"payment_status">;
          stripe_payment_intent_id: string | null;
          currency: string;
          subtotal_cents: number;
          delivery_fee_cents: number;
          tax_cents: number;
          discount_cents: number;
          tip_cents: number;
          total_cents: number;
          notes: string | null;
          scheduled_for: string | null;
          accepted_at: string | null;
          ready_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          created_at: string;
          updated_at: string;
          courier_id: string | null;
          picked_up_at: string | null;
          coupon_id: string | null;
          coupon_code: string | null;
          waiter_id: string | null;
          cash_settled_at: string | null;
          cash_settled_by: string | null;
          paid_at: string | null;
          paid_by: string | null;
          paid_method: Enums<"payment_method"> | null;
          cancelled_by: string | null;
          paid_cents: number;
          refunded_cents: number;
          manual_discount_cents: number;
          discount_reason: string | null;
          discount_by: string | null;
          delivery_failed_at: string | null;
          delivery_failed_reason: string | null;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          table_id?: string | null;
          customer_id?: string | null;
          public_token?: string;
          code: string;
          type?: Enums<"order_type">;
          status?: Enums<"order_status">;
          customer_name?: string | null;
          customer_phone?: string | null;
          customer_email?: string | null;
          address?: string | null;
          address_notes?: string | null;
          lat?: number | null;
          lng?: number | null;
          payment_method?: Enums<"payment_method">;
          payment_status?: Enums<"payment_status">;
          stripe_payment_intent_id?: string | null;
          currency?: string;
          subtotal_cents?: number;
          delivery_fee_cents?: number;
          tax_cents?: number;
          discount_cents?: number;
          tip_cents?: number;
          total_cents?: number;
          notes?: string | null;
          scheduled_for?: string | null;
          accepted_at?: string | null;
          ready_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          courier_id?: string | null;
          picked_up_at?: string | null;
          coupon_id?: string | null;
          coupon_code?: string | null;
          waiter_id?: string | null;
          cash_settled_at?: string | null;
          cash_settled_by?: string | null;
          paid_at?: string | null;
          paid_by?: string | null;
          paid_method?: Enums<"payment_method"> | null;
          cancelled_by?: string | null;
          paid_cents?: number;
          refunded_cents?: number;
          manual_discount_cents?: number;
          discount_reason?: string | null;
          discount_by?: string | null;
          delivery_failed_at?: string | null;
          delivery_failed_reason?: string | null;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          table_id?: string | null;
          customer_id?: string | null;
          public_token?: string;
          code?: string;
          type?: Enums<"order_type">;
          status?: Enums<"order_status">;
          customer_name?: string | null;
          customer_phone?: string | null;
          customer_email?: string | null;
          address?: string | null;
          address_notes?: string | null;
          lat?: number | null;
          lng?: number | null;
          payment_method?: Enums<"payment_method">;
          payment_status?: Enums<"payment_status">;
          stripe_payment_intent_id?: string | null;
          currency?: string;
          subtotal_cents?: number;
          delivery_fee_cents?: number;
          tax_cents?: number;
          discount_cents?: number;
          tip_cents?: number;
          total_cents?: number;
          notes?: string | null;
          scheduled_for?: string | null;
          accepted_at?: string | null;
          ready_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          courier_id?: string | null;
          picked_up_at?: string | null;
          coupon_id?: string | null;
          coupon_code?: string | null;
          waiter_id?: string | null;
          cash_settled_at?: string | null;
          cash_settled_by?: string | null;
          paid_at?: string | null;
          paid_by?: string | null;
          paid_method?: Enums<"payment_method"> | null;
          cancelled_by?: string | null;
          paid_cents?: number;
          refunded_cents?: number;
          manual_discount_cents?: number;
          discount_reason?: string | null;
          discount_by?: string | null;
          delivery_failed_at?: string | null;
          delivery_failed_reason?: string | null;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          restaurant_id: string;
          subscription_id: string | null;
          plan_id: string | null;
          amount_cents: number;
          currency: string;
          status: Enums<"payment_status">;
          stripe_checkout_id: string | null;
          stripe_payment_intent_id: string | null;
          stripe_invoice_id: string | null;
          paid_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          subscription_id?: string | null;
          plan_id?: string | null;
          amount_cents: number;
          currency?: string;
          status?: Enums<"payment_status">;
          stripe_checkout_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          paid_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          subscription_id?: string | null;
          plan_id?: string | null;
          amount_cents?: number;
          currency?: string;
          status?: Enums<"payment_status">;
          stripe_checkout_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          paid_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          interval: Enums<"plan_interval">;
          price_cents: number;
          currency: string;
          trial_days: number;
          max_tables: number | null;
          max_products: number | null;
          max_staff: number | null;
          allows_3d: boolean;
          allows_delivery: boolean;
          features: Json;
          stripe_price_id: string | null;
          stripe_product_id: string | null;
          is_active: boolean;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          interval: Enums<"plan_interval">;
          price_cents: number;
          currency?: string;
          trial_days?: number;
          max_tables?: number | null;
          max_products?: number | null;
          max_staff?: number | null;
          allows_3d?: boolean;
          allows_delivery?: boolean;
          features?: Json;
          stripe_price_id?: string | null;
          stripe_product_id?: string | null;
          is_active?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          interval?: Enums<"plan_interval">;
          price_cents?: number;
          currency?: string;
          trial_days?: number;
          max_tables?: number | null;
          max_products?: number | null;
          max_staff?: number | null;
          allows_3d?: boolean;
          allows_delivery?: boolean;
          features?: Json;
          stripe_price_id?: string | null;
          stripe_product_id?: string | null;
          is_active?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      products: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          description: string | null;
          price_cents: number;
          compare_at_cents: number | null;
          image_url: string | null;
          gallery: Json;
          model_3d_url: string | null;
          model_ar_url: string | null;
          model_scale: number;
          prep_minutes: number;
          calories: number | null;
          ingredients: string[];
          allergens: string[];
          tags: string[];
          rating: number;
          rating_count: number;
          is_available: boolean;
          is_featured: boolean;
          position: number;
          created_at: string;
          updated_at: string;
          catalog_category_id: string | null;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          name: string;
          description?: string | null;
          price_cents: number;
          compare_at_cents?: number | null;
          image_url?: string | null;
          gallery?: Json;
          model_3d_url?: string | null;
          model_ar_url?: string | null;
          model_scale?: number;
          prep_minutes?: number;
          calories?: number | null;
          ingredients?: string[];
          allergens?: string[];
          tags?: string[];
          rating?: number;
          rating_count?: number;
          is_available?: boolean;
          is_featured?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
          catalog_category_id?: string | null;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          name?: string;
          description?: string | null;
          price_cents?: number;
          compare_at_cents?: number | null;
          image_url?: string | null;
          gallery?: Json;
          model_3d_url?: string | null;
          model_ar_url?: string | null;
          model_scale?: number;
          prep_minutes?: number;
          calories?: number | null;
          ingredients?: string[];
          allergens?: string[];
          tags?: string[];
          rating?: number;
          rating_count?: number;
          is_available?: boolean;
          is_featured?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
          catalog_category_id?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          role: Enums<"app_role">;
          locale: string;
          created_at: string;
          updated_at: string;
          address: string | null;
          city: string | null;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: Enums<"app_role">;
          locale?: string;
          created_at?: string;
          updated_at?: string;
          address?: string | null;
          city?: string | null;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: Enums<"app_role">;
          locale?: string;
          created_at?: string;
          updated_at?: string;
          address?: string | null;
          city?: string | null;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          user_id: string | null;
          endpoint: string;
          p256dh: string;
          auth: string;
          city_slug: string | null;
          locale: string | null;
          created_at: string;
          last_seen_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          endpoint: string;
          p256dh: string;
          auth: string;
          city_slug?: string | null;
          locale?: string | null;
          created_at?: string;
          last_seen_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          city_slug?: string | null;
          locale?: string | null;
          created_at?: string;
          last_seen_at?: string;
        };
        Relationships: [];
      };
      ratings: {
        Row: {
          id: string;
          order_id: string;
          customer_id: string;
          target_type: Enums<"rating_target">;
          target_id: string;
          score: number;
          comment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          customer_id: string;
          target_type: Enums<"rating_target">;
          target_id: string;
          score: number;
          comment?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          customer_id?: string;
          target_type?: Enums<"rating_target">;
          target_id?: string;
          score?: number;
          comment?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      restaurant_couriers: {
        Row: {
          id: string;
          restaurant_id: string;
          courier_id: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          courier_id: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          courier_id?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      restaurant_staff: {
        Row: {
          id: string;
          restaurant_id: string;
          user_id: string;
          role: Enums<"staff_role">;
          pin: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          user_id: string;
          role?: Enums<"staff_role">;
          pin?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          user_id?: string;
          role?: Enums<"staff_role">;
          pin?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      restaurants: {
        Row: {
          id: string;
          owner_id: string | null;
          slug: string;
          name: string;
          description: string | null;
          logo_url: string | null;
          cover_url: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          city: string | null;
          country: string | null;
          lat: number | null;
          lng: number | null;
          currency: string;
          currency_decimals: number;
          locale: string;
          timezone: string;
          primary_color: string;
          cuisine_tags: string[];
          rating: number;
          rating_count: number;
          avg_prep_minutes: number;
          delivery_enabled: boolean;
          pickup_enabled: boolean;
          dinein_enabled: boolean;
          delivery_fee_cents: number;
          min_order_cents: number;
          tax_rate: number;
          accepts_cash: boolean;
          accepts_card: boolean;
          accepts_tpv: boolean;
          opening_hours: Json;
          is_active: boolean;
          is_open: boolean;
          created_at: string;
          updated_at: string;
          city_slug: string | null;
          accent_color: string;
          text_color: string;
          print_settings: Json;
          sound_settings: Json | null;
          document_type: string | null;
          document_number: string | null;
        };
        Insert: {
          id?: string;
          owner_id?: string | null;
          slug: string;
          name: string;
          description?: string | null;
          logo_url?: string | null;
          cover_url?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          country?: string | null;
          lat?: number | null;
          lng?: number | null;
          currency?: string;
          currency_decimals?: number;
          locale?: string;
          timezone?: string;
          primary_color?: string;
          cuisine_tags?: string[];
          rating?: number;
          rating_count?: number;
          avg_prep_minutes?: number;
          delivery_enabled?: boolean;
          pickup_enabled?: boolean;
          dinein_enabled?: boolean;
          delivery_fee_cents?: number;
          min_order_cents?: number;
          tax_rate?: number;
          accepts_cash?: boolean;
          accepts_card?: boolean;
          accepts_tpv?: boolean;
          opening_hours?: Json;
          is_active?: boolean;
          is_open?: boolean;
          created_at?: string;
          updated_at?: string;
          city_slug?: string | null;
          accent_color?: string;
          text_color?: string;
          print_settings?: Json;
          sound_settings?: Json | null;
          document_type?: string | null;
          document_number?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string | null;
          slug?: string;
          name?: string;
          description?: string | null;
          logo_url?: string | null;
          cover_url?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          country?: string | null;
          lat?: number | null;
          lng?: number | null;
          currency?: string;
          currency_decimals?: number;
          locale?: string;
          timezone?: string;
          primary_color?: string;
          cuisine_tags?: string[];
          rating?: number;
          rating_count?: number;
          avg_prep_minutes?: number;
          delivery_enabled?: boolean;
          pickup_enabled?: boolean;
          dinein_enabled?: boolean;
          delivery_fee_cents?: number;
          min_order_cents?: number;
          tax_rate?: number;
          accepts_cash?: boolean;
          accepts_card?: boolean;
          accepts_tpv?: boolean;
          opening_hours?: Json;
          is_active?: boolean;
          is_open?: boolean;
          created_at?: string;
          updated_at?: string;
          city_slug?: string | null;
          accent_color?: string;
          text_color?: string;
          print_settings?: Json;
          sound_settings?: Json | null;
          document_type?: string | null;
          document_number?: string | null;
        };
        Relationships: [];
      };
      reviews: {
        Row: {
          id: string;
          restaurant_id: string;
          product_id: string | null;
          order_id: string | null;
          customer_id: string | null;
          author_name: string | null;
          rating: number;
          comment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          product_id?: string | null;
          order_id?: string | null;
          customer_id?: string | null;
          author_name?: string | null;
          rating: number;
          comment?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          product_id?: string | null;
          order_id?: string | null;
          customer_id?: string | null;
          author_name?: string | null;
          rating?: number;
          comment?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      staff_invitations: {
        Row: {
          id: string;
          restaurant_id: string;
          email: string;
          role: Enums<"staff_role">;
          as_courier: boolean;
          token: string;
          invited_by: string | null;
          accepted_at: string | null;
          accepted_by: string | null;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          email: string;
          role?: Enums<"staff_role">;
          as_courier?: boolean;
          token: string;
          invited_by?: string | null;
          accepted_at?: string | null;
          accepted_by?: string | null;
          expires_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          email?: string;
          role?: Enums<"staff_role">;
          as_courier?: boolean;
          token?: string;
          invited_by?: string | null;
          accepted_at?: string | null;
          accepted_by?: string | null;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          restaurant_id: string;
          plan_id: string | null;
          status: Enums<"subscription_status">;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          assigned_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          plan_id?: string | null;
          status?: Enums<"subscription_status">;
          current_period_start?: string;
          current_period_end: string;
          cancel_at_period_end?: boolean;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          assigned_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          plan_id?: string | null;
          status?: Enums<"subscription_status">;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          assigned_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tables: {
        Row: {
          id: string;
          restaurant_id: string;
          code: string;
          name: string;
          zone: string | null;
          seats: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          assigned_waiter_id: string | null;
          assigned_at: string | null;
          session_id: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          code: string;
          name: string;
          zone?: string | null;
          seats?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          assigned_waiter_id?: string | null;
          assigned_at?: string | null;
          session_id?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          code?: string;
          name?: string;
          zone?: string | null;
          seats?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          assigned_waiter_id?: string | null;
          assigned_at?: string | null;
          session_id?: string;
        };
        Relationships: [];
      };
      waiter_calls: {
        Row: {
          id: string;
          restaurant_id: string;
          table_id: string;
          order_id: string | null;
          type: Enums<"call_type">;
          status: Enums<"call_status">;
          note: string | null;
          attended_by: string | null;
          attended_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          table_id: string;
          order_id?: string | null;
          type?: Enums<"call_type">;
          status?: Enums<"call_status">;
          note?: string | null;
          attended_by?: string | null;
          attended_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          table_id?: string;
          order_id?: string | null;
          type?: Enums<"call_type">;
          status?: Enums<"call_status">;
          note?: string | null;
          attended_by?: string | null;
          attended_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      place_order: {
        Args: {
          p_restaurant_slug: string;
          p_items: Json;
          p_type: Enums<'order_type'>;
          p_payment_method: Enums<'payment_method'>;
          p_table_code?: string | null;
          p_customer_name?: string | null;
          p_customer_phone?: string | null;
          p_customer_email?: string | null;
          p_address?: string | null;
          p_address_notes?: string | null;
          p_notes?: string | null;
          p_tip_cents?: number;
          p_coupon_code?: string | null;
          p_table_session?: string | null;
        };
        Returns: Json;
      };
      get_order_by_token: { Args: { p_token: string }; Returns: Json };
      call_waiter: { Args: { p_table_code: string; p_type?: Enums<'call_type'>; p_note?: string | null }; Returns: Json };
      restaurant_stats: { Args: { p_restaurant_id: string; p_days?: number }; Returns: Json };
      list_cities: { Args: { [_ in never]: never }; Returns: { city: string; city_slug: string; restaurants: number }[] };
      nearest_city: { Args: { p_lat: number; p_lng: number }; Returns: { city: string; city_slug: string; distance_km: number }[] };
      home_banners: { Args: { p_city_slug?: string | null; p_limit?: number }; Returns: { id: string; title: string | null; subtitle: string | null; image_url: string; link_url: string | null; restaurant_id: string; restaurant_name: string; restaurant_slug: string }[] };
      active_notifications: { Args: { p_city_slug?: string | null }; Returns: { id: string; title: string; body: string | null; image_url: string | null; link_url: string | null; link_label: string | null }[] };
      courier_take_order: { Args: { p_order_id: string }; Returns: Json };
      courier_stats: { Args: { [_ in never]: never }; Returns: Json };
      my_courier_id: { Args: { [_ in never]: never }; Returns: string | null };
      validate_coupon: {
        Args: {
          p_code: string;
          p_restaurant_slug: string;
          p_items: Json;
          p_type: Enums<'order_type'>;
          p_tip_cents?: number;
        };
        Returns: Json;
      };
      table_bill: { Args: { p_table_code: string }; Returns: Json };
      accept_staff_invitation: { Args: { p_token: string }; Returns: Json };
      invitation_preview: { Args: { p_token: string }; Returns: Json };
      home_categories: { Args: { p_city_slug?: string | null; p_limit?: number }; Returns: { id: string; name: string; slug: string; image_url: string | null; products: number }[] };
      restaurant_couriers_available: {
        Args: { p_restaurant_id: string };
        Returns: {
          courier_id: string;
          name: string;
          avatar_url: string | null;
          phone: string | null;
          vehicle: string;
          status: Enums<'courier_status'>;
          active_here: number;
          active_total: number;
          deliveries: number;
          rating: number;
        }[];
      };
      assign_order_courier: { Args: { p_order_id: string; p_courier_id: string }; Returns: Json };
      platform_stats: { Args: { p_days?: number }; Returns: Json };
      restaurant_analytics: { Args: { p_restaurant_id: string; p_from: string; p_to: string }; Returns: Json };
      floor_status: { Args: { p_restaurant_id: string }; Returns: Json };
      my_coupons: { Args: { [_ in never]: never }; Returns: Json };
      order_rating_targets: { Args: { p_order_id: string }; Returns: Json };
      table_session_alive: { Args: { p_code: string; p_session: string }; Returns: boolean };
      courier_picked_up: { Args: { p_order_id: string }; Returns: Json };
      courier_deliver_order: { Args: { p_order_id: string }; Returns: Json };
      courier_cash_due: { Args: { p_courier_id?: string | null }; Returns: Json };
      settle_courier_cash: { Args: { p_courier_id: string; p_restaurant_id: string }; Returns: Json };
      mark_order_paid: { Args: { p_order_id: string; p_method?: Enums<'payment_method'> }; Returns: Json };
      cancel_order: { Args: { p_order_id: string; p_reason: string }; Returns: Json };
      can_charge: { Args: { rid: string }; Returns: boolean };
      can_cancel_orders: { Args: { rid: string }; Returns: boolean };
      add_order_payment: { Args: { p_order_id: string; p_method?: Enums<'payment_method'>; p_amount_cents?: number | null; p_note?: string | null }; Returns: Json };
      pay_table_bill: { Args: { p_table_id: string; p_method?: Enums<'payment_method'>; p_amount_cents?: number | null; p_note?: string | null }; Returns: Json };
      refund_order: { Args: { p_order_id: string; p_reason: string; p_amount_cents?: number | null; p_method?: Enums<'payment_method'> }; Returns: Json };
      void_order_item: { Args: { p_item_id: string; p_reason: string }; Returns: Json };
      apply_manual_discount: { Args: { p_order_id: string; p_cents: number; p_reason: string }; Returns: Json };
      courier_fail_delivery: { Args: { p_order_id: string; p_reason: string }; Returns: Json };
      restaurant_cash_due: { Args: { p_restaurant_id: string }; Returns: Json };
      open_cash_session: { Args: { p_restaurant_id: string; p_float_cents?: number; p_note?: string | null }; Returns: Json };
      close_cash_session: { Args: { p_session_id: string; p_counted_cents: number; p_note?: string | null }; Returns: Json };
      add_cash_movement: { Args: { p_restaurant_id: string; p_kind: Enums<'cash_movement_kind'>; p_amount_cents: number; p_reason: string; p_method?: Enums<'payment_method'> }; Returns: Json };
      cash_session_report: { Args: { p_session_id: string }; Returns: Json };
      current_cash_session: { Args: { p_restaurant_id: string }; Returns: Json };
      cash_sessions_list: { Args: { p_restaurant_id: string; p_limit?: number }; Returns: Json };
      money_audit_list: { Args: { p_restaurant_id: string; p_limit?: number }; Returns: Json };
      expected_cash: { Args: { p_session_id: string }; Returns: number };
      is_superadmin: { Args: { [_ in never]: never }; Returns: boolean };
      is_staff_of: { Args: { rid: string }; Returns: boolean };
    };
    Enums: {
      app_role: "superadmin" | "restaurant" | "customer" | "courier";
      call_status: "pending" | "attended" | "cancelled";
      call_type: "waiter" | "bill" | "water" | "help";
      cash_movement_kind: "payout" | "withdrawal" | "deposit" | "courier_settlement" | "tip_out" | "correction" | "other";
      cash_session_status: "open" | "closed";
      coupon_kind: "percentage" | "fixed" | "free_delivery";
      coupon_target: "order" | "products" | "categories";
      courier_status: "offline" | "available" | "busy";
      notification_audience: "all" | "cities";
      order_item_status: "queued" | "preparing" | "ready" | "served";
      order_status: "pending" | "confirmed" | "preparing" | "ready" | "served" | "delivering" | "completed" | "cancelled";
      order_type: "dine_in" | "delivery" | "pickup";
      payment_entry_kind: "charge" | "refund";
      payment_method: "cash" | "card" | "tpv" | "stripe";
      payment_status: "pending" | "paid" | "failed" | "refunded";
      plan_interval: "month" | "year";
      rating_target: "restaurant" | "product" | "courier" | "waiter";
      staff_role: "owner" | "admin" | "manager" | "waiter" | "kitchen" | "cashier";
      subscription_status: "trialing" | "active" | "past_due" | "canceled" | "expired";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
